name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed

jobs:
  delivery:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create Release Folder
        run: |
          mkdir release
          cp ParkApp.py release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: parkapp-release
          path: release/